In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
h_train = pd.read_csv("housing_train.csv")
h_train.head()

CRIM    ZN  INDUS  CHAS  NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0   0.13960   0.0   8.56   0.0  NaN  6.167  90.0  2.4210    5  384.0      NaN   
1   0.03510  95.0   2.68   0.0  NaN  7.853  33.2  5.1180    4  224.0      NaN   
2  15.87440   0.0  18.10   0.0  NaN  6.545  99.1  1.5192   24  666.0      NaN   
3   0.18337   0.0  27.74   0.0  NaN  5.414  98.3  1.7554    4  711.0      NaN   
4   0.12816  12.5   6.07   0.0  NaN  5.885  33.0  6.4980    4  345.0      NaN   

        B  LSTAT        MEDV  
0  392.69    NaN   86.066034  
1  392.78    NaN  207.700057  
2  396.90  21.08   46.689349  
3  344.05  23.97   29.980669  
4  396.90    NaN   89.461275

In [3]:
h_validation = pd.read_csv("housing_validation.csv")
h_validation.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.09178   0.0   4.05   0.0    NaN  6.416  84.1  2.6463    5  296.0   
1  0.05644  40.0   6.41   1.0    NaN  6.758  32.9  4.0776    4  254.0   
2  0.10574   0.0  27.74   0.0    NaN  5.983  98.8  1.8681    4  711.0   
3  0.09164   0.0  10.81   0.0    NaN  6.065   7.8  5.2873    4  305.0   
4  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682   24  666.0   

   PTRATIO       B  LSTAT  
0      NaN  395.50    NaN  
1      NaN  396.90    NaN  
2      NaN  390.11  18.07  
3      NaN  390.91    NaN  
4      NaN  385.09    NaN

In [4]:
h_example = pd.read_csv("housing_example_submission.csv")
h_example

MEDV
0   0.31337
1   0.31337
2   0.31337
3   0.31337
4   0.31337
..      ...
71  0.31337
72  0.31337
73  0.31337
74  0.31337
75  0.31337

[76 rows x 1 columns]

In [5]:
h_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     430 non-null    float64
 1   ZN       430 non-null    float64
 2   INDUS    430 non-null    float64
 3   CHAS     408 non-null    float64
 4   NOX      52 non-null     float64
 5   RM       430 non-null    float64
 6   AGE      430 non-null    float64
 7   DIS      430 non-null    float64
 8   RAD      430 non-null    int64  
 9   TAX      420 non-null    float64
 10  PTRATIO  420 non-null    float64
 11  B        430 non-null    float64
 12  LSTAT    88 non-null     float64
 13  MEDV     430 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 47.2 KB


In [6]:
h_train.shape

(430, 14)

In [7]:
430*0.7

301.0

In [142]:
h_train['B'].isna().value_counts()

False    430
Name: B, dtype: int64

In [11]:
h_train["NA_in_col_NOX"] = h_train["NOX"].isna().astype(int)
h_train.head()

CRIM    ZN  INDUS  CHAS  NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0   0.13960   0.0   8.56   0.0  NaN  6.167  90.0  2.4210    5  384.0      NaN   
1   0.03510  95.0   2.68   0.0  NaN  7.853  33.2  5.1180    4  224.0      NaN   
2  15.87440   0.0  18.10   0.0  NaN  6.545  99.1  1.5192   24  666.0      NaN   
3   0.18337   0.0  27.74   0.0  NaN  5.414  98.3  1.7554    4  711.0      NaN   
4   0.12816  12.5   6.07   0.0  NaN  5.885  33.0  6.4980    4  345.0      NaN   

        B  LSTAT        MEDV  NA_in_col_NOX  
0  392.69    NaN   86.066034              1  
1  392.78    NaN  207.700057              1  
2  396.90  21.08   46.689349              1  
3  344.05  23.97   29.980669              1  
4  396.90    NaN   89.461275              1

In [12]:
h_train["NA_in_col_NOX"].value_counts()

1    378
0     52
Name: NA_in_col_NOX, dtype: int64

In [13]:
h_train['NA_in_col_LSTAT'] = h_train['LSTAT'].isna().astype(int)
h_train.head()

CRIM    ZN  INDUS  CHAS  NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0   0.13960   0.0   8.56   0.0  NaN  6.167  90.0  2.4210    5  384.0      NaN   
1   0.03510  95.0   2.68   0.0  NaN  7.853  33.2  5.1180    4  224.0      NaN   
2  15.87440   0.0  18.10   0.0  NaN  6.545  99.1  1.5192   24  666.0      NaN   
3   0.18337   0.0  27.74   0.0  NaN  5.414  98.3  1.7554    4  711.0      NaN   
4   0.12816  12.5   6.07   0.0  NaN  5.885  33.0  6.4980    4  345.0      NaN   

        B  LSTAT        MEDV  NA_in_col_NOX  NA_in_col_LSTAT  
0  392.69    NaN   86.066034              1                1  
1  392.78    NaN  207.700057              1                1  
2  396.90  21.08   46.689349              1                0  
3  344.05  23.97   29.980669              1                0  
4  396.90    NaN   89.461275              1                1

In [14]:
h_train['NA_in_col_LSTAT'].value_counts()

1    342
0     88
Name: NA_in_col_LSTAT, dtype: int64

In [15]:
h_train = h_train.drop(columns=['NOX', 'LSTAT'])
h_train.head()

CRIM    ZN  INDUS  CHAS     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0   0.13960   0.0   8.56   0.0  6.167  90.0  2.4210    5  384.0      NaN   
1   0.03510  95.0   2.68   0.0  7.853  33.2  5.1180    4  224.0      NaN   
2  15.87440   0.0  18.10   0.0  6.545  99.1  1.5192   24  666.0      NaN   
3   0.18337   0.0  27.74   0.0  5.414  98.3  1.7554    4  711.0      NaN   
4   0.12816  12.5   6.07   0.0  5.885  33.0  6.4980    4  345.0      NaN   

        B        MEDV  NA_in_col_NOX  NA_in_col_LSTAT  
0  392.69   86.066034              1                1  
1  392.78  207.700057              1                1  
2  396.90   46.689349              1                0  
3  344.05   29.980669              1                0  
4  396.90   89.461275              1                1

In [17]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression

In [144]:
X = h_train.drop(columns=['MEDV'])
y = h_train['MEDV']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [19]:
h_train.head()

CRIM    ZN  INDUS  CHAS     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0   0.13960   0.0   8.56   0.0  6.167  90.0  2.4210    5  384.0      NaN   
1   0.03510  95.0   2.68   0.0  7.853  33.2  5.1180    4  224.0      NaN   
2  15.87440   0.0  18.10   0.0  6.545  99.1  1.5192   24  666.0      NaN   
3   0.18337   0.0  27.74   0.0  5.414  98.3  1.7554    4  711.0      NaN   
4   0.12816  12.5   6.07   0.0  5.885  33.0  6.4980    4  345.0      NaN   

        B        MEDV  NA_in_col_NOX  NA_in_col_LSTAT  
0  392.69   86.066034              1                1  
1  392.78  207.700057              1                1  
2  396.90   46.689349              1                0  
3  344.05   29.980669              1                0  
4  396.90   89.461275              1                1

In [20]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 322 entries, 3 to 102
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CRIM             322 non-null    float64
 1   ZN               322 non-null    float64
 2   INDUS            322 non-null    float64
 3   CHAS             303 non-null    float64
 4   RM               322 non-null    float64
 5   AGE              322 non-null    float64
 6   DIS              322 non-null    float64
 7   RAD              322 non-null    int64  
 8   TAX              316 non-null    float64
 9   PTRATIO          315 non-null    float64
 10  B                322 non-null    float64
 11  NA_in_col_NOX    322 non-null    int32  
 12  NA_in_col_LSTAT  322 non-null    int32  
dtypes: float64(10), int32(2), int64(1)
memory usage: 32.7 KB


In [22]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 108 entries, 422 to 307
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CRIM             108 non-null    float64
 1   ZN               108 non-null    float64
 2   INDUS            108 non-null    float64
 3   CHAS             105 non-null    float64
 4   RM               108 non-null    float64
 5   AGE              108 non-null    float64
 6   DIS              108 non-null    float64
 7   RAD              108 non-null    int64  
 8   TAX              104 non-null    float64
 9   PTRATIO          105 non-null    float64
 10  B                108 non-null    float64
 11  NA_in_col_NOX    108 non-null    int32  
 12  NA_in_col_LSTAT  108 non-null    int32  
dtypes: float64(10), int32(2), int64(1)
memory usage: 11.0 KB


In [145]:
imputer = SimpleImputer(strategy="median")
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [146]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Model linear regression")
print(f"Model MSE: {mean_squared_error(y_test, y_pred)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred)}")

Model linear regression
Model MSE: 545.2891053143301
Model RMSE: 23.35142619443896
Model MAE: 16.250163664889786


In [32]:
obs = pd.DataFrame({
    'CRIM': [3.69],
    'ZN': [11.37],
    'INDUS': [11.15],
    'CHAS': [0.07],
    'NOX': [0.87],
    'RM': [6.29],
    'AGE': [68.91],
    'DIS': [3.77],
    'RAD': [9.50],
    'TAX': [410.95],
    'PTRATIO': [18.37],
    'B': [354.47],
    'LSTAT': [0.79],
})
obs

CRIM     ZN  INDUS  CHAS   NOX    RM    AGE   DIS  RAD     TAX  PTRATIO  \
0  3.69  11.37  11.15  0.07  0.87  6.29  68.91  3.77  9.5  410.95    18.37   

        B  LSTAT  
0  354.47   0.79

In [33]:
obs["NA_in_col_NOX"] = obs["NOX"].isna().astype(int)
obs

CRIM     ZN  INDUS  CHAS   NOX    RM    AGE   DIS  RAD     TAX  PTRATIO  \
0  3.69  11.37  11.15  0.07  0.87  6.29  68.91  3.77  9.5  410.95    18.37   

        B  LSTAT  NA_in_col_NOX  
0  354.47   0.79              0

In [34]:
obs['NA_in_col_LSTAT'] = obs['LSTAT'].isna().astype(int)
obs

CRIM     ZN  INDUS  CHAS   NOX    RM    AGE   DIS  RAD     TAX  PTRATIO  \
0  3.69  11.37  11.15  0.07  0.87  6.29  68.91  3.77  9.5  410.95    18.37   

        B  LSTAT  NA_in_col_NOX  NA_in_col_LSTAT  
0  354.47   0.79              0                0

In [35]:
obs = obs.drop(columns=['NOX', 'LSTAT'])
obs

CRIM     ZN  INDUS  CHAS    RM    AGE   DIS  RAD     TAX  PTRATIO       B  \
0  3.69  11.37  11.15  0.07  6.29  68.91  3.77  9.5  410.95    18.37  354.47   

   NA_in_col_NOX  NA_in_col_LSTAT  
0              0                0

In [36]:
y_obs = model.predict(obs)
y_obs

C:\Users\Aga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([63.25974104])

In [41]:
obs2 = imputer.transform(obs)
obs2

C:\Users\Aga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SimpleImputer was fitted without feature names
  warnings.warn(


array([[3.6900e+00, 1.1370e+01, 1.1150e+01, 7.0000e-02, 6.2900e+00,
        6.8910e+01, 3.7700e+00, 9.5000e+00, 4.1095e+02, 1.8370e+01,
        3.5447e+02, 0.0000e+00, 0.0000e+00]])

In [42]:
y_obs2 = model.predict(obs2)
y_obs2

array([63.25974104])

In [43]:
obs3 = pd.DataFrame({
    'CRIM': [3.69],
    'ZN': [11.37],
    'INDUS': [11.15],
    'CHAS': [0.07],
    'NOX': [0.87],
    'RM': [8.29],
    'AGE': [68.91],
    'DIS': [3.77],
    'RAD': [9.50],
    'TAX': [410.95],
    'PTRATIO': [18.37],
    'B': [354.47],
    'LSTAT': [0.79],
})
obs3

CRIM     ZN  INDUS  CHAS   NOX    RM    AGE   DIS  RAD     TAX  PTRATIO  \
0  3.69  11.37  11.15  0.07  0.87  8.29  68.91  3.77  9.5  410.95    18.37   

        B  LSTAT  
0  354.47   0.79

In [44]:
obs3["NA_in_col_NOX"] = obs3["NOX"].isna().astype(int)
obs3['NA_in_col_LSTAT'] = obs3['LSTAT'].isna().astype(int)
obs3 = obs3.drop(columns=['NOX', 'LSTAT'])
obs3

CRIM     ZN  INDUS  CHAS    RM    AGE   DIS  RAD     TAX  PTRATIO       B  \
0  3.69  11.37  11.15  0.07  8.29  68.91  3.77  9.5  410.95    18.37  354.47   

   NA_in_col_NOX  NA_in_col_LSTAT  
0              0                0

In [45]:
y_obs3 = model.predict(obs3)
y_obs3

C:\Users\Aga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([115.48881864])

In [46]:
115.48881864-63.25974104

52.229077600000004

In [47]:
from sklearn.svm import NuSVR
from sklearn.tree import DecisionTreeRegressor

In [48]:
model2 = NuSVR()
model2.fit(X_train, y_train)

model3 = DecisionTreeRegressor()
model3.fit(X_train, y_train)

y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)


In [49]:
print("Model NuSVR")
print(f"Model MSE: {mean_squared_error(y_test, y_pred2)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred2))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred2)}")

Model NuSVR
Model MSE: 1472.2997945114328
Model RMSE: 38.37055895489969
Model MAE: 25.530144717046227


In [50]:
print("Model decision tree regressor")
print(f"Model MSE: {mean_squared_error(y_test, y_pred3)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred3))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred3)}")

Model decision tree regressor
Model MSE: 451.88531351303436
Model RMSE: 21.257594255066454
Model MAE: 14.50344876764832


In [52]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
model4 = RandomForestRegressor()
model4.fit(X_train, y_train)
y_pred4 = model4.predict(X_test)
print("Model RandomForstRegressor")
print(f"Model MSE: {mean_squared_error(y_test, y_pred4)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred4))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred4)}")

Model RandomForstRegressor
Model MSE: 401.43058356869994
Model RMSE: 20.03573266862732
Model MAE: 13.451323437998887


In [63]:
reg = xgb.XGBRegressor(tree_method="gpu_hist")
reg.fit(X_train, y_train)
y_pred_reg = reg.predict(X_test)
print("Model XGB")
print(f"Model MSE: {mean_squared_error(y_test, y_pred_reg)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_reg))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred_reg)}")

Model XGB
Model MSE: 340.6675041623934
Model RMSE: 18.457180287421842
Model MAE: 12.819261108077606


In [57]:
pip install xgboost

     ------------------------------------- 125.4/125.4 MB 21.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Aga\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [58]:
import xgboost as xgb

In [106]:
reg2 = xgb.XGBRegressor(tree_method="gpu_hist", max_bin= 20, )
reg2.fit(X_train, y_train)
y_pred_reg2 = reg2.predict(X_test)
print("Model XGB")
print(f"Model MSE: {mean_squared_error(y_test, y_pred_reg2)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_reg2))}")
print(f"Model MAE: {mean_absolute_error(y_test, y_pred_reg2)}")

Model XGB
Model MSE: 236.1325300380576
Model RMSE: 15.366604375660149
Model MAE: 11.518954441219263


In [120]:
h_validation.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.09178   0.0   4.05   0.0    NaN  6.416  84.1  2.6463    5  296.0   
1  0.05644  40.0   6.41   1.0    NaN  6.758  32.9  4.0776    4  254.0   
2  0.10574   0.0  27.74   0.0    NaN  5.983  98.8  1.8681    4  711.0   
3  0.09164   0.0  10.81   0.0    NaN  6.065   7.8  5.2873    4  305.0   
4  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682   24  666.0   

   PTRATIO       B  LSTAT  
0      NaN  395.50    NaN  
1      NaN  396.90    NaN  
2      NaN  390.11  18.07  
3      NaN  390.91    NaN  
4      NaN  385.09    NaN

In [121]:
h_validation["NA_in_col_NOX"] = h_validation["NOX"].isna().astype(int)
h_validation['NA_in_col_LSTAT'] = h_validation['LSTAT'].isna().astype(int)
h_validation = h_validation.drop(columns=['NOX', 'LSTAT'])
h_validation.head()

CRIM    ZN  INDUS  CHAS     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0  0.09178   0.0   4.05   0.0  6.416  84.1  2.6463    5  296.0      NaN   
1  0.05644  40.0   6.41   1.0  6.758  32.9  4.0776    4  254.0      NaN   
2  0.10574   0.0  27.74   0.0  5.983  98.8  1.8681    4  711.0      NaN   
3  0.09164   0.0  10.81   0.0  6.065   7.8  5.2873    4  305.0      NaN   
4  5.09017   0.0  18.10   0.0  6.297  91.8  2.3682   24  666.0      NaN   

        B  NA_in_col_NOX  NA_in_col_LSTAT  
0  395.50              1                1  
1  396.90              1                1  
2  390.11              1                0  
3  390.91              1                1  
4  385.09              0                1

In [143]:
h_validation.shape

(76, 13)

In [122]:
h_validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CRIM             76 non-null     float64
 1   ZN               76 non-null     float64
 2   INDUS            76 non-null     float64
 3   CHAS             73 non-null     float64
 4   RM               76 non-null     float64
 5   AGE              76 non-null     float64
 6   DIS              76 non-null     float64
 7   RAD              76 non-null     int64  
 8   TAX              76 non-null     float64
 9   PTRATIO          0 non-null      float64
 10  B                76 non-null     float64
 11  NA_in_col_NOX    76 non-null     int32  
 12  NA_in_col_LSTAT  76 non-null     int32  
dtypes: float64(10), int32(2), int64(1)
memory usage: 7.2 KB


In [147]:
h_validation = imputer.transform(h_validation)

In [148]:
y_pred_val = reg2.predict(h_validation)


In [149]:
y_pred_val

array([101.02839 , 124.982346,  36.69515 ,  92.83369 ,  91.0175  ,
        98.71778 ,  81.61328 ,  70.24969 ,  89.94553 ,  91.91998 ,
        77.46302 ,  77.37355 ,  59.13392 ,  93.91867 ,  83.96998 ,
       135.30159 ,  84.54383 ,  61.602257, 211.35277 ,  63.585823,
       106.73745 , 109.04024 ,  74.03983 , 102.31589 ,  69.742065,
        54.870174,  88.99287 ,  54.459995,  95.43906 ,  93.013626,
        85.76837 , 103.13358 , 101.77223 ,  87.19311 ,  60.304256,
        71.8896  , 164.90189 ,  85.30699 ,  91.57175 ,  99.80765 ,
        87.38543 , 132.54016 , 218.04996 ,  76.31424 ,  94.45487 ,
        69.272705,  67.840004,  98.23575 ,  95.745346, 106.17888 ,
        81.59862 , 133.5841  ,  77.03726 , 105.54719 , 149.31694 ,
        90.65624 ,  84.56567 , 137.98973 ,  99.05111 ,  67.89081 ,
       101.689095, 155.7839  , 127.36032 ,  70.4983  , 101.31432 ,
        71.62828 ,  76.084045, 102.908104, 120.50805 ,  64.277725,
        91.579185, 110.22052 ,  33.713596,  86.50147 ,  93.522

In [150]:
h_example

MEDV
0   0.31337
1   0.31337
2   0.31337
3   0.31337
4   0.31337
..      ...
71  0.31337
72  0.31337
73  0.31337
74  0.31337
75  0.31337

[76 rows x 1 columns]

In [153]:
y_pred_val_df = pd.DataFrame(y_pred_val, columns=["MEDV"])
y_pred_val_df

MEDV
0   101.028389
1   124.982346
2    36.695148
3    92.833687
4    91.017502
..         ...
71  110.220520
72   33.713596
73   86.501472
74   93.522636
75   28.210201

[76 rows x 1 columns]

In [154]:
y_pred_val_df.to_csv("Roj_pred.csv", index=False)

In [107]:
from sklearn.preprocessing import Normalizer

In [108]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, random_state=42)

In [111]:
normal = Normalizer()
X_train_2 = normal.fit_transform(X_train_2)
X_test_2 = normal.transform(X_test_2)

In [110]:
imputer = SimpleImputer(strategy="median")
X_train_2 = imputer.fit_transform(X_train_2)
X_test_2 = imputer.transform(X_test_2)

In [114]:
model_new1 = LinearRegression()
model_new1.fit(X_train_2, y_train_2)
y_pred_new1 = model_new1.predict(X_test_2)

print("Model linear regression")
print(f"Model MSE: {mean_squared_error(y_test_2, y_pred_new1)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test_2, y_pred_new1))}")
print(f"Model MAE: {mean_absolute_error(y_test_2, y_pred_new1)}")

Model linear regression
Model MSE: 531.9580176301705
Model RMSE: 23.064215088100667
Model MAE: 16.011516310318413


In [119]:
reg2_next = xgb.XGBRegressor(tree_method="gpu_hist")
reg2_next.fit(X_train_2, y_train_2)
y_pred_reg2_next = reg2_next.predict(X_test_2)
print("Model XGB")
print(f"Model MSE: {mean_squared_error(y_test_2, y_pred_reg2_next)}")
print(f"Model RMSE: {np.sqrt(mean_squared_error(y_test_2, y_pred_reg2_next))}")
print(f"Model MAE: {mean_absolute_error(y_test_2, y_pred_reg2_next)}")

Model XGB
Model MSE: 265.06648838915135
Model RMSE: 16.280862642659674
Model MAE: 11.922770313551602
